
service: static-site-mailer

functions:
  staticSiteMailer:
    handler: handler.staticSiteMailer
    memorySize: 256
    events:
      - http:
          method: post
          path: static-site-mailer
          cors: true

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}
  runtime: nodejs18.x
  tracing:
    lambda: true
  iam:
    Role:
      Statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource: ["*"]
